version: '3.5'
services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./webapp
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://test:test@db/test
    networks:
      - default
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app/webapp
networks:
  default:
    driver: bridge